version: "3"
services:
 dind:
  image: docker:dind
  privileged: true
  expose:
  - 2375
 jenkins:
  image: jenkins:docker
  ports:
  - "8080:8080"
  - "50000:50000"
  links:
  - dind
  environment:
  - DOCKER_HOST=tcp://dind:2375
  volumes: 
  - /Users/garg.v/prod/jenkins/keys/jenkins/:/var/jenkins_home/.ssh
 clientBox:
  image: rastasheep/ubuntu-sshd:18.04
  command: sh
  volumes: 
  - /Users/garg.v/prod/jenkins/keys/clientBox/:/root/.ssh
  ports: 
  - "32768:22"
  tty: true
